# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- alembic-jekyll-theme.gemspec

# 2. Installed Gems
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

# 3. Gem settings
paginate: 2 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page
social: # jekyll-seo-tag > social overrides
  links:  # jekyll-seo-tag > social aliases (sameAs)


# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: America/Mexico_City # Timezone for blog posts and alike

# 5. Collections
collections:
  posts:
    title: Posts # Needed for Siteleaf
    output: true
    description: "Publicaciones" # The post list page content
    feature_text: |
      # BLOG

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
    values:
      image: "/assets/logo-text-on-white.png" # Default image for sharing

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: es-MX # Set the site language
title: "Comisión de Selección del Sistema Anticorrupción del Estado de Jalisco" 
        # Site name or title, also used in jekyll-seo-tag
logo: "/assets/logo.svg" # Site logo, also used in jekyll-seo-tag
description: "" 
        # Site description and default description, also used in jekyll-seo-tag
url: "http://comisionsaejalisco.org" # Site url, also used in jekyll-seo-tag
baseurl: ""
repo: "https://github.com/jaliscocomovamos/jaliscocomovamos.github.io"
avatarurl: "http://comisionsaejalisco.org/favicon.ico"
email: "lic_adrian21@hotmail.com"
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

# 8. Site navigation
navigation_header:
  Quiénes Somos: /quienes_somos/
  Comunicados: /comunicados-2018/
  Convocatoria: 
  Formatos: 
  Marco Legal: /marco_legal/
  Calendario: /calendario/
  Contacto: /contacto/

navigation_footer:
  # Created by Jalisco Cómo Vamos: http://jaliscocomovamos.org/

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  Twitter: javascript:void(0)
  Facebook: javascript:void(0)
  # LinkedIn: https://www.linkedin.com/in/daviddarnes
  # Google+: https://plus.google.com/+DavidDarnes
  # GitHub: https://github.com/daviddarnes
  # link: https://darn.es
  # RSS: /feed.xml

sharing_links: # Appear at the bottom of single blog posts, uncomment and comment out as desired. Colours set the button colour
  # Twitter: "#1DA1F2"
  # facebook: "#3B5998"
  # Google+: "#DC4E41"
  # Pinterest: "#BD081C"
  # LinkedIn: "#0077B5"
  # tumblr: "#36465D"
  # Reddit: "#FF4500"
  # Hacker News: "#ff6600"
  # Designer News: "#2D72D9"
  # Email: ""

# Add Google Analytics
google_analytics: UA-107378701-1

# Additional instructions
remote_theme: daviddarnes/alembic


